models:
  - type: main
    engine: openai
    model: solidrust/Mistral-7B-Instruct-v0.3-AWQ 
    parameters:
          # This points to your local 4060 Ti vLLM instance
          openai_api_base: "http://vllm:8000/v1"
          #openai_api_base: "http://localhost:8000/v1"
          openai_api_key: "local-machine"    
          max_tokens: 1024
          temperature: 0.1
          stop: ["user:", "Assistant:", "\n\n"]


instructions:
  - type: general
    content: |
      You are a helpful and polite AI assistant. 
      You stay on topic and provide concise answers.
core:
  parameters:
    temperature: 0.1
    max_tokens: 512
